apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile
  namespace: build-pipeline
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /tmp/kaniko # replace with local directory, such as "/home/<user-name>/kaniko"
